# Generated by Django 5.2.14 on 2026-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('carrera', models.CharField(choices=[('SIS', 'Ingenieria en Sistemas'), ('SOF', 'Ingenieria en Software'), ('IND', 'Ingenieria Industrial'), ('ADM', 'Administracion'), ('CON', 'Contabilidad')], default='SIS', max_length=3, verbose_name='Carrera')),
                ('semestre', models.PositiveSmallIntegerField(default=1, verbose_name='Semestre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
